### ISSUE TITLE
good but non-original 'OP on/off' behavior?

### ISSUE THREAD

**Issue by N871** [asb2m10/dexed#106]
In Dexed, the 'OP output levels' are computed for every note-on which is also how the original dx7 worked. In other words when a key is pressed down, changing the OP output levels doesn't affect the sound, until you replay the note or add a few notes (in which case the added notes will have the new output level and the first held note still has the 'old' output level'.

I don't have a dx7 but on my TX816 the OP on/off buttons work in the same way. They only affect the sound for new notes played after the on/off buttons were changed. If I hold a note and change these buttons the sound is not affected. 

In Dexed however the sound changes immediately, which is in fact a good thing (=direct feedback). But because the output level knobs work the same way as the original DX7/TX816 I thought it might be overlooked that the OP on/off buttons work in the same way..AT LEAST ON MY TX816. Could be that is worked differently on the DX7, but I don't think so as the TX816 came out two years later and still has this 'vintage' parameter change behavior.

that's all :)

**Comment by asb2m10** [comment]
Just tested this on my DX7 Mark I and you are right, the OP switch is computed on "note on". This means that Dexed is not following the same implementation. That said, Dexed also supports dynamic EG change and operator level, the DX7 does not. 

I have no plan to remove those features since they are very useful to design a FM sound. I'm pretty sure users wouldn't be too happy to lose this. I know that sometimes I put the DX7 behaviour first but this time it is an 'editing feature'. And, one of the reason I've made Dexed was not having to use my DX7 for editing patches.

Sorry but the direct feedback as you call will stay as-is.
