### ISSUE TITLE
Operator on/off state not correctly sent to volcaFM

### ISSUE THREAD

**Issue by subv0x** [asb2m10/dexed#155]
Hi, 
sending presets to volcaFM, the operator on/off states 
are often wrong. have not checked if any pattern in this. 
cheers !

**Comment by coffeeshopped** [comment]
The Volca FM stores operator on/off data in the preset data itself. The DX7 does not! So, where do the seemingly-random on/off states in the Volca FM come from when sending a DX7 preset to it? ...

The second-to-last byte in a preset sysex message is used by the DX7 to store a checksum (basically, a number used to verify that the data got transmitted correctly). Korg decided to instead use this byte to store operator on/off data for presets.

So, the Volca FM is reading the checksum of a DX7 patch and interpreting it as operator on/off data, when in fact for every DX7 preset, all of the operators should always be turned on.

**Comment by subv0x** [comment]
nice one, detective :tu:
use this to blackmail korg into doing us a firmware that allows 
single parameter messages ! or out the volcaFM as not really 
receiving DX7 presets :D is there any difference between an 
operator being Off and having zero level? probably not.

didn't realise DX7 needed a checksum. (does the TX802?)

at least we know that the other parameters are probably ok. 
really didn't realise OP on/off was not stored :(

**Comment by coffeeshopped** [comment]
I make editors for these synths, so I've gotten to know the sysex of them pretty well. :)

I'm not sure if there's a difference between an op being off or having a zero level. I would think they'd be the same, but there's always the possibility of some idiosyncrasy in the synth...

Yeah, the TX802 needs it as well. All of those old Yamahas have a checksum byte at the end of the sysex data. If the checksum is incorrect, they'll give you an error message and not load the patch you sent.

Dexed could theoretically add a "Volca FM" mode that always sends full patches (instead of individual parameter updates), and uses the checksum area the way Korg decided to. Might be a good feature request?

**Comment by asb2m10** [comment]
Sorry for the late reply but there is an unofficial volcafm firmware that fixes this: https://ranzee.com/volca-fm-firmware-1-09-unofficial/

**Comment by subv0x** [comment]
yes! thank you. i participated in resolving that, testing for 'pajen' (Petter), giving feedback over several versions.

    On Monday, 6 July 2020, 04:56:17 CEST, Pascal Gauthier <notifications@github.com> wrote:  
 
 


Sorry for the late reply but there is an unofficial volcafm firmware that fixes this: https://ranzee.com/volca-fm-firmware-1-09-unofficial/
