### ISSUE TITLE
iOS port?

### ISSUE THREAD

**Issue by rcarmo** [asb2m10/dexed#168]
I'm curious as to what it would entail to port this to iOS. Are there any plans for it?

**Comment by asb2m10** [comment]
Yes/No. Technically it is a JUCE app so it should be somewhat straight forward to do. But it is more complex than that:

* I would have to purchase a JUCE and Apple developer license to do so (cannot release GPL software on the app store). I don't want to sell dexed since I don't have the time to support it.
* UI that is statically defined and working on this would take time especially since there is a UI makeover in the future. 

Hope this answer your question...
