### ISSUE TITLE
MPE support

### ISSUE THREAD

**Issue by tobia** [asb2m10/dexed#176]
Just leaving this here for any good soul who would like to try their hands at it.

From Wikipedia:

> MIDI Polyphonic Expression (MPE) is a method of using MIDI that enables pitch bend, and other dimensions of expressive control, to be adjusted continuously for individual notes. MPE works by assigning each note to its own MIDI channel so that particular messages can be applied to each note individually.
>
> Instruments like the Continuum Fingerboard, Linnstrument, ROLI Seaboard, and Eigenharp let users control pitch, timbre, and other nuances for individual notes within chords. A growing number of soft synths and effects are also compatible with MPE, as well as a few hardware synths.

Here is [Roger Linn's explanation](http://www.rogerlinndesign.com/mpe.html) on why MPE was needed.

Here is the [MIDI Association's article](https://www.midi.org/articles-old/midi-polyphonic-expression-mpe) with a link to the ***technical specification*** (free registration required to download it.) The specification goes to great lengths to describe zones, master channels, and other concepts, so I think it's an essential resource for anybody interested in implementing this.

I'm thinking about getting one of these fancy new controllers and I'd love to use Dexed with it. Unfortunately, I did some tests in Bitwig and I couldn't get per-note pitch bend to work, no matter how I set up the MIDI channels or MPE settings. It's probably something that needs to be addressed in Dexed's code.

**Comment by jpcima** [comment]
I'm tempted to give this a try, however I dont' own any sort of MPE controller.
Are you able to record an example MIDI file of playing with MPE? (including initialization sequence)

**Comment by TjShredder** [comment]
I am not sure if this is the right place. I wonder why this issue is still listed open, as MPE works fine for me with my LinnStrument. But there is a little quirk. When I load Dexed and open the Parameters window to switch on MPE the image suggests that MPE is already switched on (but it isn't). If I toggle it, it seemingly toggles the state of the image and the state of MPE. But they are contradictory. As soon I close the window and reopen. The state and image seem to be synchronized and the image reflects that MPE is on and then it works... Beside fixing this glitch I recommend to set the default MPE bend range to 48, as that is the default. 
I observe that glitch on OSX Mojave and Bitwig 3.3.3

**Comment by tank-trax** [comment]
@TjShredder the MPE feature was implemented by the Surge Synth Team

could you please open an issue [here](https://github.com/surge-synthesizer/dexed/issues)

Thanks

**Comment by asb2m10** [comment]
I forgot to close this. Dexed support MPE since 0.9.5
