### ISSUE TITLE
Possible GPL violoation - iOS version of Dexed

### ISSUE THREAD

**Issue by mtytel** [asb2m10/dexed#187]
Hey so I saw that someone released an iOS version of dexed. Seeing that the original is licensed under the GPLv3 and that the App Store is not compatible with it I thought I'd reach out and let you know.

http://www.georgerosar.com/dexed/
https://apps.apple.com/app/id1462551596?ign-mpt=uo%3D8

**Comment by kroaton** [comment]
They are also charging 4$ for it and there is no mention of any source code release anywhere.

**Comment by Lucretia** [comment]
Request the source from them, they have to abide by that. It's not a GPL violation to offer a binary for money, not sure about any violations re the store itself.

**Comment by asb2m10** [comment]
The source is here: https://github.com/8888clockradio/Dexed-ios, but there is no iOS builds.

It is not possible to sell GPL software on the App Store: https://apple.stackexchange.com/a/59495 

The only way to sell Dexed on the App Store or a port of it is to change the license and to do that the copywriters have to agree for the license change. I and we did not. 

I will ask JUCE what they think of this since their code is also GPL....

**Comment by Lucretia** [comment]
> The source is here: https://github.com/8888clockradio/Dexed-ios, but there is no iOS builds.

So request them, that's what the GPL is for.

> It is not possible to sell GPL software on the App Store: https://apple.stackexchange.com/a/59495

It's possible to sell support for GPL'd software see Red Hat, Suse, AdaCore, and yes, it is possible to sell GPL'd software, it's allowed.

> The only way to sell Dexed on the App Store or a port of it is to change the license and to do that the copywriters have to agree for the license change. I and we did not.

No, it's really not. The issue is with the Store's licence and how it (or doesnt) interact with the GPL. If the licence is incompatible with the GPL, then the guy selling Dexed is in Breach of the Apple licence, most likely.
 
> I will ask JUCE what they think of this since their code is also GPL....

...
