### ISSUE TITLE
Plugin doesn't set VST unique ID

### ISSUE THREAD

**Issue by sagamusix** [asb2m10/dexed#20]
I noticed that Dexed seems to share the same plugin ID as another JUCE-based VST, so I guess you both forgot to actually set a unique ID for the plugin.

**Comment by asb2m10** [comment]
Changes commited in 0.8.1 branch

**Comment by frognerboy** [comment]
Could this be linked with why my Ableton Live projects using pre AU version of Dexed now gives the error message "The VST plugin could be found" ever since updating newer version of Dexed? To be clear, Dexed loads perfectly except when loading earlier projects. I ask as I need to find the .syx patches used in those earlier projects. (Mac)
