### ISSUE TITLE
DEXED for Windows and screen reader accessibility for blind users

### ISSUE THREAD

**Issue by Luke-Robinett** [asb2m10/dexed#238]
Hi. I'm blind and rely on special software called a screen reader to access my computer. In simple terms, a screen reader speaks aloud the contents of the screen as the user navigates using the keyboard. I find that the DEXED VST plugin for Windows does not support screen readers nor keyboard navigation, from what I can tell. I don't need access to all the deep editing parameters because I can easily map those to physical controls on my MIDI controller, but I do need the ability to load cartridges and programs easily and I cannot figure out how to do this without being able to see the DEXED UI. Is there some way the program can be enhanced to allow blind users to load carts and programs? Even if there's a way I can open the Cartridges folder in Windows, right-click the cartridge I want and maybe have a "Load in DEXED" context menu option appear, for example. Thank you for any help/ideas.

**Comment by asb2m10** [comment]
The entire user interface is based on [JUCE](https://juce.com/), which is a common framework used by developers to make plugins. Adding those features would require me to modify this framework and afterward maintain it. 

I've double check and JUCE doesn't yet support screen readers but they are aware that users are asking for this feature. I would suggest that you add your voice to some of the issue that is already [opened](https://github.com/juce-framework/JUCE/issues/289).

Also, I see that "Pro Users" of JUCE are taking seriously accessibility in this [survey](https://forum.juce.com/t/the-2019-juce-user-survey-results/32407) for 2019. Let's hope they are working on this.

Once it is included in JUCE, I will make sure we support the accessibility API correctly.

>Is there some way the program can be enhanced to allow blind users to load carts and programs? Even if there's a way I can open the Cartridges folder in Windows, right-click the cartridge I want and maybe have a "Load in DEXED" context menu option appear, for example.

I can add a keyboard shortcut that would open the Windows file chooser in the Dexed cartridge folder and from there you could load the file (cartridge). This is easy to implement.

**Comment by Luke-Robinett** [comment]
Hi Pascal,
I truly appreciate this thorough and helpful response! I will take your advice on reaching out to the developers of that software framework for more assistance. I also like the idea you have for providing keyboard access to loading cartridges. Frankly I don’t plan on messing around much with the FM parameters, and I can already access those by mapping them to my physical controller, so it’s really just loading modules. I really just want to throw in some DX7 factory sounds and call it good, as that fits the needs of the project I’m working on.

Thanks again!

**Comment by Luke-Robinett** [comment]
Hi, @asb2m10 ,

It's been a while but I was messing around with Dexed again recently and wondered if you're aware of any updates to the framework? You mentioned in your older reply about adding a keyboard shortcut to show the file browse dialog for loading a model - did you have a chance to add that? Thanks again!

**Comment by pbsinnett** [comment]
Hi,

Figured I'd comment here instead of opening a new issue for the same thing. The latest version of Juce has definitely implemented accessibility.

Would it be possible to look into making this wonderful plug-in accessible? I've included a link to the Juce accessibility docs below.

https://docs.juce.com/master/group__juce__gui__basics-accessibility.html

I'd be more than happy to help test any accessibility related changes.

Thanks!

**Comment by asb2m10** [comment]
Hi @pbsinnett  and @Luke-Robinett 

I'm currently implementing accessibility for Dexed and your input will be essential since I have no background in this field. I will soon provide "developer builds" that you will be able to use and off course provide feedback.

From what I understood, keyboard navigation is essential right ? What platform should I focus on testing, macOS or Windows ? What is the right "accessibility" that I should enable on my side depending on the OS ?

The guys at Surge-Synth project were kind enough to provide a #dexed channel on their discord server in the "Surge Synth Friends" category. Feel free to discuss this over there.

https://discord.com/invite/spGANHw

I'm waiting for you feedback.
