### ISSUE TITLE
Fix Dexed's logo

### ISSUE THREAD

**Issue by uzr123x** [asb2m10/dexed#240]
can you please fix the "dexed" logo that's displayed in Dexed's main window and make it look tidy once and for all? In previous versions, the top parts of its "e"s were cut off and made it look odd, in the current version, its first "d" is cut off and the logo looks blurry for some reason. I think this is such a slapdash treatment for such a good synthesizer.

**Comment by giacecco** [comment]
Hi @uzr123x , I'm not dexed's maitainer but if you look at the [source file](https://github.com/asb2m10/dexed/blob/master/Resources/ui/source/dexed-logo.xcf) you can see that the cut-off "e"s are intentional. You may not like it, but that's the way it was designed 😀

About the logo looking blurry, you can also see that the master file is a 640x213 bitmap, that's quite a small file for modern high-res screens. Probably the maintainer would need to re-make the logo for scratch if he wanted it to look better, unless he stored somewhere else than Github a better version of the same file, possibly vectorial.

**Comment by uzr123x** [comment]
Hey there, thanks for pointing out these details, giacecco

> Hi @uzr123x , I'm not dexed's maitainer but if you look at the [source file](https://github.com/asb2m10/dexed/blob/master/Resources/ui/source/dexed-logo.xcf) you can see that the cut-off "e"s are intentional. You may not like it, but that's the way it was designed 😀

well, then this part of my question can be omitted. It was an old version's logo anyway. Still, my complaint about the new blurry logo remains valid.

> About the logo looking blurry, you can also see that the master file is a 640x213 bitmap, that's quite a small file for modern high-res screens. Probably the maintainer would need to re-make the logo for scratch if he wanted it to look better, unless he stored somewhere else than Github a better version of the same file, possibly vectorial.

I've seen some really nice-looking Dexed logos on the web, like this one: https://img.informer.com/icons_mac/png/128/447/447120.png
Also a suggestion, why not make an official logo entirely in vector and forget about all bitmap issues?

**Comment by mkruselj** [comment]
Yes the cutout is intentional AFAIK.

But, it should at least be aligned!

![image](https://user-images.githubusercontent.com/2393720/110207840-3c75c280-7e86-11eb-91ff-72361bbd8f62.png)

See how the X is lower than Es? Should all be a straight line.

**Comment by asb2m10** [comment]
This will be fixed when #233 will be implemented.
