### ISSUE TITLE
where can I find x86 dll?

### ISSUE THREAD

**Issue by AldairCB** [asb2m10/dexed#252]
I wanted to first thank you, this is a great vst and I´ve been using for almsot a year and I love it. I used to had the x86 version installed but accidently unninstalled it and now when I redownloaded it it´s only the x64 version. Now all my projects don´t match with the current version

**Comment by shooking** [comment]
I guess you could try building from scratch? It depends on whether Projucer can generate x86 make files? And if there are implicit 64 bit code.

Since the original DX7 was not 64 bit it might work.
Or get a Raspberry Pi4 and build your own little midi box? I made a video on doing that here https://youtu.be/9IUUzV516kQ

**Comment by asb2m10** [comment]
I think the issue that the project doesn't match is because Dexed is now VST3 only. VST3 cannot share VST2 state.

Sorry but this is because Steingberg dropped VST2 and I cannot build updated version of Dexed with VST2.

Old version are still available.
