### ISSUE TITLE
Dexed 0.8.0 doesn't start on Mac OSX 10.6.8

### ISSUE THREAD

**Issue by JurekRaben** [asb2m10/dexed#27]
If I try to load the dexed vst version 0.8.0 on Mac OSX 10.6.8, it will break up with an error. Version 0.7.0 works fine on 10.6.8... Can you fix it? Thanks. BTW. you can target also 10.6.8 if compiling on more recent OSX xcode versions by placing the old OSX 10.6.8 sdk to the appropriate directory (taking from the old xcode version).

**Comment by asb2m10** [comment]
I thought that it was already 10.6 'enabled'; I cannot test it on my side since I don't have any 10.6 machines.

Sorry about that but the build tool is always resetting the XCode build and I can miss these parameters (I use 10.7 and I can force it to handle 10.6 API)... I will fix this in 0.8.1. 

I will post the 0.8.1 beta on KVR; if you (or others 10.6 users) can be there to test it before the official build gets released, it would be very appreciated.

**Comment by tmonkz** [comment]
Hello, looks like great work on the dexed!! hats off... will there be a (64 bit) au version? or better off a stand alone version for mac? trying to load this on a 10.10.1 OS X with no success so far. or maybe I'm doing something wrong? in any case , thanks a lot for keeping dx editing alive!

**Comment by JurekRaben** [comment]
Yes, I will test it on 10.6.8.

**Comment by JurekRaben** [comment]
Please see my message on KVR.

**Comment by tmonkz** [comment]
in what thread please? thx

**Comment by JurekRaben** [comment]
No, PM to asb2m10...

**Comment by tmonkz** [comment]
oops

**Comment by asb2m10** [comment]
I've taken care to check for the 10.6 SDK. Please check on the BETA to be sure that the build is ok : http://le-son666.com/software/dexed/dexed-0.9-beta-osx.zip

**Comment by JurekRaben** [comment]
Hi, sorry don't use 10.6.8 anymore ;) But still a bunch of people do, for good reasons. Is it working there now?
