### ISSUE TITLE
dexed automations/ Sysex to Tx802 in ableton 

### ISSUE THREAD

**Issue by AngiePalazotto** [asb2m10/dexed#299]
Hello, I have a TX802 and when I run dexed in **standalone** it is possible to vary the TX parameters via the dexed knobs (SysEx going directly midi out the TX ...) great ;)

(_I want to make ableton automations for dexed parameters and root the midi out to the harware synth._)
However it is impossible for me to do the same operation via vst in ableton. I'm looking for a solution to root dexed midi out of LIVE (11).

I read that live does not communicate sysex messages
(see here: https://help.ableton.com/hc/en-us/articles/360003148640-SysEx-support-in-Live-10)

So I bought a max4live dx7 editor which can vary the parameters of the TX via live it works ...
(https://maxforlive.com/library/device/6223/dx7-editor)
This editor does not take the automations of special parameters (osc tune, etc ...) = i am asking a friend to modify the Mac Object to have all automation but Dexed is better and it's implemented so....

Si it's impossible for me to root the midi out of the pluging...

**Comment by asb2m10** [comment]
Ableton describe this behavior this pretty well:
> Do I need Max for Live to use SysEx in Live?
Yes. Starting with Live 10, Live supports SysEx messages through suitable Max for Live devices only.

So it is not a plugin but a Max4Live device that can send sysex. If I know that a DAW that I run (Bitwig, Reaper, Renoise, Logic, Live), I'll do what is needed to route the sysex message to the plugin. Until then, I avoid putting this *feature* since no DAW that I know supports it.
