### ISSUE TITLE
Default Cartridge Directory? 

### ISSUE THREAD

**Issue by JefferyWright** [asb2m10/dexed#320]
Why can't we choose where this is located?

**Comment by asb2m10** [comment]
Because the user could provide a directory the program doesn't have the access (E.G. C:\Program Files on Windows, /Library/Audio/Plugin... on mac OS) and this leads to user headaches.

It is easier to select a directory that we know that the OS will allow the plugin to access. If you are on mac OS, you can put symbolic link.
