### ISSUE TITLE
Cannot open resultant .so file in LMMS or Carla

### ISSUE THREAD

**Issue by pnewbery** [asb2m10/dexed#329]
I have managed to compile the Linux dexed.so file but find I am unable to use it in either LMMS or Carla under Linux Mint 20.3. (NOT using Wine!) The file is simply not recognized in LMMS and the error I get in Carla is "Could not find the VST main entry in the plugin library".
I have been able to successfully load the Colab3 and oxefmsynth.so files in Carla, but not in LMMS directly, but am able to use them in LMMS via the Carla Rack.

**Comment by pnewbery** [comment]
I have done some investigation and discovered that LMMS does not support VST3 which is what the Dexed VST is. However, Carla does support them and therefore should be able to run Dexed. That being the case, I should be able to use Dexed in LMMS via Carla. So the issue is now about getting Dexed to work in Carla.

**Comment by Rinkaa** [comment]
I think LMMS doesn't support native Linux VSTs in their releases by now? The pull request (https://github.com/LMMS/lmms/pull/6048) was merged but not very long ago

**Comment by pnewbery** [comment]
@Rinkaa Thanks for your reply. I've read the request you mentioned, but don't see any reference to pulling support for .so files, quite the opposite in fact. DomClark's post of 3rd March said 

    Only complaint I have as a user is that I must select *.so instead of *.dll in the browser every time 
"I will address this in a future PR (also removing *.exe from that list because it makes no sense)."

So Dom will be looking at _improving_ .so support and _removing_ .exe support. Unfortunately, that doesn't seem to have happened just yet. 
Having checked my copy of LMMS, I do not see the option for .so files in the VeSTige browser window in my installation of LMMS 1.3.0-alpha.1.102. The only choices I see are .dll and .exe files. So if the .exe option is removed I will only be able to open .dll files in Linux, which seems rather odd to say the least.

**Comment by Rinkaa** [comment]
> So Dom will be looking at _improving_ .so support and _removing_ .exe support. Unfortunately, that doesn't seem to have happened just yet. Having checked my copy of LMMS, I do not see the option for .so files in the VeSTige browser window in my installation of LMMS 1.3.0-alpha.1.102. The only choices I see are .dll and .exe files. So if the .exe option is removed I will only be able to open .dll files in Linux, which seems rather odd to say the least.

The PR is not _improving_ .so support. It is actually _adding_ .so support. The .so support did not exist at all before those commits. At least that PR is the only one (among the several attempts for adding .so support by various people) that has made it to the master branch. 
I don't think that PR is included in the version 1.3.0-alpha, because the version 1.3.0-alpha.1(the last release in Apr 2021) came out before the PR was merged(Mar 2022) and there can't be any chance to include a new feature (i.e. supporting .so VSTs) without increasing the version number.
Even in the **Linux** version of LMMS, VeSTige currently functions only for loading **Windows 32bit** VST2s, by implicitly using WINE for bridging inbetween. To remove .exe support looks like a minor enhancement for the existing filter in the browser window. 
Since LMMS 1.3.0-alpha simply cannot load native Linux VST .so files at all, I don't agree it is an issue that dexed needs to fix. I suggest we simply wait for the next major release of LMMS and see.
I haven't tried this by myself but maybe you can try compiling dexed to a Windows 32bit VST .dll file and see if it loads in the Linux version of LMMS 1.3.0.

**Comment by asb2m10** [comment]
I'm closing this since it is not related to Dexed current (VST3) offering.
