### ISSUE TITLE
request: UI size

### ISSUE THREAD

**Issue by ghost** [asb2m10/dexed#363]
Hi

Thank you for dexed!
I'm using a 4K pc monitor and dexed is very little in this resolution: tiny buttons and very small text. So it's not comfortable to work with.

Can I request a feature (like most synth VSTs have) to enlarge the user interface to 110%, 120%, ... up to 200%?

Thank you

**Comment by tranzedude** [comment]
On a Mac with monitor that has larger then 4K resolution, the dexed window is even more tiny!
So this feature is highly needed for high resolution monitors.

**Comment by NTMan** [comment]
I am noted that the last version use upscaling (it looks pretty soapy) but when I press "PARM" button plugin interface forgets about upscaling.

Demonstration:
[Screencast from 2023-01-01 03-17-47.webm](https://user-images.githubusercontent.com/200750/210156607-d751808a-921a-4676-925e-3d35c8a34294.webm)

**Comment by Audiojunkie** [comment]
Yes, clear HiDPI scaling on all 3 OSes would be really appreciated! 🙂

**Comment by Audiojunkie** [comment]
Hello!  😀 I am a Linux user that has been wanting to use Dexed for a long time, but the screen is too small for my 4k laptop monitor.  My last post was nearly a year ago, because I didn't want to be a bother--since I know you are busy.  😀

The last release, 0.9.6, was in March of 2021. I know that you started working on 0.9.7, but there hasn't been a release for over a year and a half.  Would it be possible to do an interim release (maybe something like 0.9.6.5) and release the GUI fixes, and wait on the other things for a 0.9.7 release?  I would really love to use this wonderful instrument. Thank you!

**Comment by asb2m10** [comment]
Dexed now supports upscaling now to 400%

Please test here : https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4

**Comment by NTMan** [comment]
> Dexed now supports upscaling now to 400%
> 
> Please test here : https://github.com/asb2m10/dexed/releases/tag/v0.9.7pre4


https://github.com/asb2m10/dexed/assets/200750/8ffe7820-7cf7-4c33-b974-99d9a17e74b7

Without scaling (100%), when the dexed window appears for the for the first time, it looks like with applied scaling.
And after pressing the "PARM" button, scaling became as expected.
