### ISSUE TITLE
See name of currently loaded cartridge

### ISSUE THREAD

**Issue by probonopd** [asb2m10/dexed#379]
Is there no easy way to see the name of currently loaded cartridge? There should be.

**Comment by probonopd** [comment]
What I mean is: Expose the name of `activeFileCartridge` in the GUI.

**Comment by probonopd** [comment]
In https://github.com/asb2m10/dexed/actions/runs/10084451248 I still don't see the name of the currently loaded cartridge, e.g., in the empty space marked with a "?":

![image](https://github.com/user-attachments/assets/c3fd2b20-e242-4d14-9c77-6501d84c71ef)

**Comment by FulopNandor** [comment]
Hi @probonopd!

The name of the cartridge file is displayed in the bottom right corner of the cartridge manager window - which could be opened by a left click onto ``CART`` button -, not in the main window. 
![CartridgeFilePath](https://github.com/user-attachments/assets/8df5a95b-867e-46f4-acf0-41d329cc6a47)
And if you click onto the underlined cartridge file name there, a file browser window should be opened.

Or, if the cartridge file has been deleted/moved from its original location since the last loading, a text ``No reference to original cartridge`` should appear instead of the ``Based on cartridge ....``.

(It was built from latest commit, 8fdafa3).

**Comment by probonopd** [comment]
Thanks for the clarification. Sorry if it wasn't clear from my original post - I think the name of the cartridge should be visible in the main UI. What do you think?

**Comment by FulopNandor** [comment]
Since I unfortunately do not have enough experience with JUCE, I cannot judge how difficult it would be to display the file name in the main window instead of the cartridge manager window. So I just think it would be somewhat more complicated, because if this information were to be placed in the main window, the existence of the cartridge file would have to be checked in the background from time to time and the content updated if necessary, because for example, someone could delete/move the cartridge file using the operating system’s file explorer. And I don’t know whether the JUCE framework provides some ready-made automation for this on every platform.

**Comment by asb2m10** [comment]
If the file should be shown on the main windows, it should be over the program selector otherwise we have to much UI elements that are not organized. Having it placed diagonally from the program manager is not aesthetically correct. 
Also, there is some long filename that will be stripped; while there is plenty of space in the cartridge manager.
