### ISSUE TITLE
Feature Request: Drag and Drop sysex file to Cartdrige

### ISSUE THREAD

**Issue by waltercruz** [asb2m10/dexed#39]
I know that I should put my sysex files on a specific folder, but it would be nice import the sysex with drag and drop directy from Finder or Windows Explorer :)

**Comment by asb2m10** [comment]
Now implemented on the 0.9.1 branch... 

But I have these JUCE "FileTreeComponent" limitations : 

a) Each time you drop a file, since we need to refresh the file browser (to see the new files) this closes all of the already opened folders.

b) The drop is based on the selected file in the file component, you cannot target a directory by simply dragging the file to a specific directory with the mouse. You need to select a directory/file first, then drag the file.

Because of these limitations, I'm not convinced if this "enhancement" in that form should be included in the official 0.9.1 version...
