### ISSUE TITLE
Unable to install standalone mode on Linux Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by seymourgler** [asb2m10/dexed#424]
I have tried and tried to follow the installation instructions exactly, and install all known dependencies, but I still cannot get Dexed to install standalone mode on my Linux Ubuntu 20.04.6 LTS. I am willing to do a clean Linux install. Is there a build and/or flavor you prefer, which is known to work best for this purpose?

Thanks!

**Comment by FulopNandor** [comment]
Hi, David!Maybe this link helps:https://github.com/asb2m10/dexed/wiki/Linux-build-dependencieswhere you can find  the list of some packages, which ones should be installed before issuing the ``cmake``  commands.Note, that there is only ``-build-`` without ``s`` in the name of the link. -------- Eredeti levél --------Feladó: David Seymour ***@***.***>Dátum: 2024 május 29 03:12:51Tárgy: [asb2m10/dexed] Unable to install standalone mode on Linux Ubuntu 20.04.6 LTS (Issue #424)Címzett: asb2m10/dexed ***@***.***>I have tried and tried to follow the installation instructions exactly, and install all known dependencies, but I still cannot get Dexed to install standalone mode on my Linux Ubuntu 20.04.6 LTS. I am willing to do a clean Linux install. Is there a build and/or flavor you prefer, which is known to work best for this purpose?Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by FulopNandor** [comment]
Hi again, David!

Today (May 29, 2024) I also cloned and built Dexed from this repository in Raspberry Pi 4B with Raspbian OS Bookworm 64-bit. However I have not experienced any problems related to either the repo or the instructions provided. As I noticed meantime that you have problems, I made a detailed description what I have done. I enclose it (there is a  plain text file inside the zip):
[RPI4B.zip](https://github.com/asb2m10/dexed/files/15484944/RPI4B.zip)
it might be of help to you.

**Comment by asb2m10** [comment]
Hi @seymourgler, is it build issue or a runtime issue. Please post error message.

**Comment by seymourgler** [comment]
Thanks guys! It was classic user error, or at least user _confusion_. Yes, I had successfully installed all the Linux build dependencies: libx11-dev, libcurl4-gnutls-dev, libfreetype6-dev, libasound2-dev, libxinerama-dev, libjack-jackd2-dev, libxcursor-dev, libxrandr-dev, and even the optional webkit2gtk-4.0 and gtk+-x11-3.0. The build seemed to complete successfully, no stopping and no error messages.

I found the executable binary in the /dexed/build/Source/Dexed_artefacts folder, but I was navigating through the GUI and falsely assumed I could just double-click on the Dexed file, which gave the following pop-up, "Could not display Dexed. There is no application installed for shared library files. Do you want to search for an application to open this file?"

When I read FulopNandor's instructions more closely, I navigated to the directory in the terminal and successfully opened it with "./Dexed"

But to that point, is it possible to make standalone Dexed appear among the installed Linux apps, with an icon that can be added to the Favorites bar?

Thanks again!
