### ISSUE TITLE
Please use 'find(JUCE REQURED)' instead of bundling it

### ISSUE THREAD

**Issue by yurivict** [asb2m10/dexed#432]
JUCE provides the 'install' target, and it is discoverable with `find(JUCE REQURED)`.

There should be no reason to bundle it. Bundling is not sustainable in general, because it causes potentially exponential downloads of all hierarchical dependencies.

The bundled JUCE requires some patches on FreeBSD, while we have the working juce-8.0.0 package available.

**Comment by asb2m10** [comment]
I used to work a system wide JUCE installation and it was very difficult to maintain because I have to keep a JUCE installation on 3 different platform and it was very cumbersome to work with. Secondo, I have different plugins projects that might use a specific JUCE version; I don't want to reinstall that specific JUCE version each time I have to work with that project. Finally, for new users, a "git clone --recurse-submodules" + "cmake" just works out of the box; and it makes the CI stuff way simpler.

That said, if you do a pull request that simply adds 'find(JUCE REQURED)' if a CMAKE variable is set, I'll be more than happy to merge it.
