### ISSUE TITLE
Feature Request: LV2 version for Raspberry Pi

### ISSUE THREAD

**Issue by connortreacy** [asb2m10/dexed#45]
I'd love to build a standalone Dexed host based on a Raspberry Pi, but I don't know where to start building for LV2 on ARM. Anyone willing to help?

**Comment by timoteoramos** [comment]
Hexter seems to be a "fast" alternative, but I love Dexed too and it will be good to see Dexed running as a LV2 plugin.

**Comment by timoteoramos** [comment]
Hexter seems to be a "fast" alternative - DSSI plugin, not LV2, it runs on Raspberry Pi, I guess. But I love Dexed too and it will be good to see Dexed running as a LV2 plugin.

**Comment by asb2m10** [comment]
Check this thread for this : http://www.juce.com/forum/topic/juce-lv2-plugin-wrapper. Once you can compile LV2 on JUCE, Dexed should be trivial. We are all waiting for JUCE to officially support LV2. :|

Btw, Dexed should be an excellent plugin on the Pi since it almost do all the dsp stuff with integers.

**Comment by asb2m10** [comment]
Since Dexed is based on JUCE, it will be difficult to support all platforms (VST/AU/LV2/OSX/WIN/LNX) at the same time. I suggest to look at https://github.com/dcoredump/dexed/tree/native-lv2 ; from @dcoredump that actually port dexed to LV2.
