### ISSUE TITLE
VST 3 support

### ISSUE THREAD

**Issue by suhr** [asb2m10/dexed#51]
VST 2 is deprecated.

**Comment by mkruselj** [comment]
VST 2 is definitely not deprecated, all DAWs still support it - and will do so for years to come.

**Comment by suhr** [comment]
Indeed. It's just a part of VST3 SDK now.
Btw, it's very confusing since the makefile contains `~/src/vstsdk2.4` as VST SDK path.

**Comment by asb2m10** [comment]
My current DAW doesn't support VST3... Right now, I already do 5 independant build and that's enough testing per pre release versions.

But I don't see a problem to switch the build to support VST 3. The only thing is that I will not provide the binaires until version 1.0.

**Comment by baconbrad** [comment]
@mkruselj [According to Steinberg](https://www.steinberg.net/forums/viewtopic.php?p=628791&sid=181e3e32d350a53d05030e7d0b21c713#p628791) VST2 is deprecated. Additionally [it has been deprecated since 2013](https://dawfreak.wordpress.com/2013/09/03/steinberg-ends-development-of-vst-2/). So 5 years later it is really at the end of it's rope.

Developers still make VST2 plugins because not all DAWs have added VST3 support. But I think most now do and Ableton Live is just late to the party. We are already seeing developers no longer releasing VST2 plugins and I imagine once Live adds VST3 support we will see it more rapidly dying off.

Most DAWs still load VST2 plugins and I predict many will for a while. But it is important to note this now considered a legacy feature at this point. And DAW support for it might be a ticking time bomb.

**Comment by mkruselj** [comment]
Of course Steinberg would say that in order to push VST 3 forward. But it didn't really work out the way they intended, we only see more VST3 plugins more recently, more than 5 years after they introduce it.

The only DAWs that might drop VST2 support relatively soon are Steinberg's own. All others will extremely likely have it for years to come, I would assume until something breaks support for them in Win/macOS (also probably unlikely).

**Comment by asb2m10** [comment]
Closing this since 0.9.5 is now provided in the VST3 form.
