### ISSUE TITLE
Midi Learn

### ISSUE THREAD

**Issue by deadpahn** [asb2m10/dexed#58]
It would be great to have a midi learn feature. Since I am using this stand alone using SAVI, I would like to map some stuff to my controller.

**Comment by Gnalvl** [comment]
100% agree. I like to use savihost to reduce distraction/clutter when sound designing, and with every other vst, I use midilearn and the knobs on a novation remote to do all my programming hands-on.

In theory, one should be able to use DX7 sysex commands to get Dexed working with the Novation Remote, but in practice Dexed's "port in use" catch-22 prevents this from working. I know the issue isn't my sysex code since I used these same templates with my TX802 without problems.

Besides which, there are probably a lot of people out there who own midi controllers with no sysex capability who would love to use Dexed with midi learn. After all, the number one thing that made the original DX-7 unapproachable and hard to learn was the lack of hands-on control (aside from the mega-expensive, ultra-rare Jellinghaus controller).
