### ISSUE TITLE
Only 16bit output?

### ISSUE THREAD

**Issue by MD-78** [asb2m10/dexed#62]
0.9.1 x64 Engine Resolution set to "Modern (24 Bit)" only gives 16bit output here (REAPER 5).

**Comment by MD-78** [comment]
Culprit seems to be the Filter Cutoff.

Filter fully opened = 16 bit output

**Comment by asb2m10** [comment]
The Modern Engine does use 24bit for the internal OP calculation ; but it is brought back (from integer to float) to 16 at the end. If you see 16-bit when the filter is fully open, it is simply because the filter is bypassed.

That said, the output should be 24bit. I'll will add a fix for this in the next release.

**Comment by MD-78** [comment]
Cool, thank you!

**Comment by Iu-Gob** [comment]
Update v0.9.2b1 works 24-bit! Thanks a lot Pascal! Regards

**Comment by MD-78** [comment]
FIXED (0.9.2)
