### ISSUE TITLE
Read error  - unable to read file

### ISSUE THREAD

**Issue by Drytowelman** [asb2m10/dexed#89]
When I click STORE > EXTERNAL FILE > and choose a cartridge I get the above error message.

I recently downloaded and installed the newest version of dexed and i think this may have something to do with.

Any help appreciated!

**Comment by asb2m10** [comment]
The version 0.9.2 is very picky in terms of sysex id ; to make it work, open the target catridge and re save-it. It will put the default DX7 header id and will work afterwards.

The next version will not have this issue since it will be more permissive; the ID won't be check anymore but only the filesize and checksum.

**Comment by Drytowelman** [comment]
Super thanks!

**Comment by asb2m10** [comment]
Please check with this version : https://github.com/asb2m10/dexed/releases/tag/v0.9.3b1 to confirm that it is no longer an issue.

Thanks.

**Comment by Drytowelman** [comment]
Thanks - I'll test tonight and report back

Ray

**Comment by Drytowelman** [comment]
Hi - this works as expected.  Many thanks!
