### ISSUE TITLE
ft2build.h not found

### ISSUE THREAD

**Issue by ipofanes** [asb2m10/dexed#91]
While compiling for Linux, the following error message appears:

../../JuceLibraryCode/modules/juce_graphics/juce_graphics.cpp:82:24: fatal error: ft2build.h: Datei oder Verzeichnis nicht gefunden

indeed a file named ft2build.h is not in the directory tree. 

Last commit was:

commit 8620531b01289271c50f54b3ad1b335362f8a785
Author: asb2m10
Date:   Wed Mar 1 23:34:53 2017 -0500

**Comment by asb2m10** [comment]
Seems that freetype modified something... similar error on Arch Linux.

The Dexed JUCE library is getting old (more than one year) and I won't change this since I will upgrade it in the next release. If it still fails with the new version of JUCE; I'll change the Makefile to make it work.

Otherwise on my side, it was able to build it by adding '-I /usr/include/freetype2 and -l /usr/include/freetype2/freetype' to gcc.

**Comment by asb2m10** [comment]
Dexed is now using JUCE 4.3.1 and this is no longer an issue when building Dexed.
